metadata:
  robot: ffw_bg2_rev4_follower
  captured_at: ''        # ISO 8601, set by capture node
  generator: ''          # script + version, set by capture node

offsets:  # bit values
  # RIGHT ARM
  dxl1: 35648            # arm_r_joint1
  dxl2: 552                # arm_r_joint2
  dxl3: 34604            # arm_r_joint3
  dxl4: 442                # arm_r_joint4
  dxl5: 0                # arm_r_joint5
  dxl6: -267                # arm_r_joint6
  dxl7: -836                # arm_r_joint7

  # LEFT ARM
  dxl31: 31401           # arm_l_joint1
  dxl32: -50               # arm_l_joint2
  dxl33: 33115           # arm_l_joint3
  dxl34: -4570               # arm_l_joint4
  dxl35: 0               # arm_l_joint5
  dxl36: 1904               # arm_l_joint6
  dxl37: 203               # arm_l_joint7

  #32768